### ISSUE TITLE
Webpack builds in monorepos are broken

### ISSUE THREAD

**Issue by svyatogor** [Nikaple/nest-typed-config#205]
## I'm submitting a...

<pre><code>
[ ] Regression 
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

Using this nest-typed-config in nestjs monorepo, which are built with web pack results. In `class-validator` library not being found due to dynamic loading. Previous version exhibited similar behaviour for `dotenv`, but it was easier to work around by providing own loader.

## Expected behavior

Webpack builds should not fail.

## Environment

<pre><code>
Nest version: 9.0.0

 
For Tooling issues:
- Node version: 16  

Others:

</code></pre>

**Comment by Nikaple** [comment]
Please provide an minimum reproduction repo to help better investigation.

**Comment by floogulinc** [comment]
I am also having an issue with this when my Nest app is installed globally.
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'class-validator'
Require stack:
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\dist\utils\imports.util.js
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\dist\typed-config.module.js
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\dist\index.js
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\index.js
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\dist\app.module.js
- C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at requireFromRootNodeModules (C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\dist\utils\imports.util.js:5:32)
    at Object.<anonymous> (C:\Users\floogulinc\AppData\Roaming\nvm\v16.15.0\node_modules\hyshare\node_modules\nest-typed-config\dist\utils\imports.util.js:9:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\node_modules\\nest-typed-config\\dist\\utils\\imports.util.js',
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\node_modules\\nest-typed-config\\dist\\typed-config.module.js',
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\node_modules\\nest-typed-config\\dist\\index.js',
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\node_modules\\nest-typed-config\\index.js',
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\dist\\app.module.js',
    'C:\\Users\\floogulinc\\AppData\\Roaming\\nvm\\v16.15.0\\node_modules\\hyshare\\dist\\main.js'
  ]
}
```
